### PR TITLE
GCS Durability

### PR DESCRIPTION
**Pull request by nelsonjchen**
https://cloud.google.com/storage/

### CODE REVIEW

**Comment by andrewgaul** [comment]
Sorry, can you show me a reference for this SLA?  I only see:

https://cloud.google.com/storage/sla

**Comment by nelsonjchen** [comment]
Would this paragraph on the linked page do it? 

Google Cloud Storage is incredibly durable, 99.999999999%; multiple copies, multiple locations with checksums and cross region striping of data.

Though huh, I guess I don't see it on the page that's about the SLA though, just the marketing one.

**Comment by andrewgaul** [comment]
Yes, sorry I missed this paragraph!

**Comment by andrewgaul** [comment]
Pushed to master as 1badb0cdc09a51f9c2200797f16281ac19bc5680.

**Pull request closed without merging**
